### ISSUE TITLE
Address missing dependency WARNINGs

### ISSUE THREAD

**Issue by traversaro** [conda-forge/gazebo-feedstock#136]
### Comment:

Reported by @hmaarrfk in https://github.com/conda-forge/gazebo-feedstock/pull/135#issuecomment-1146860268 .

**Comment by traversaro** [comment]
> To be clear. I think this may be the cause of the segfaults your users are seeing

Ack, so it may be related to:
* https://github.com/conda-forge/gazebo-feedstock/issues/125
* https://github.com/conda-forge/gazebo-feedstock/issues/119

**Comment by hmaarrfk** [comment]
Yes. some of these may have gotten migrated, and we didn't migrate `gazebo`. So it is expecting symbols that aren't there.
