### ISSUE TITLE
FFMPEG 5 migration stalled

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/gazebo-feedstock#155]
### Comment:

Just a little FYI that the FFMPEG migration is stalled here.

You can check the status at: https://conda-forge.org/status/#other_migrations

Seems like some of the harsh pinnings are causing the solver to not converge.

**Comment by Tobias-Fischer** [comment]
See #157

**Comment by traversaro** [comment]
Thanks @Tobias-Fischer and @hmaarrfk !
