### ISSUE TITLE
libignition-common3 missing libignition-common3-graphics.so.3

### ISSUE THREAD

**Issue by wolfv** [conda-forge/gazebo-feedstock#35]
For some reason we are missing this graphics library in libignition-common3 which seems to prevent gazebo 11 from starting (on Linux).
Any ideas?

**Comment by Tobias-Fischer** [comment]
Yes - this will be fixed once https://github.com/conda-forge/libignition-common-feedstock/pull/14 is merged (it's very annoying that we have to manually add glib in addition to gts in this case ..). Once @seanyen merges this we should be good to go.
