### ISSUE TITLE
On Windows, can't insert model from Fuel Database

### ISSUE THREAD

**Issue by traversaro** [conda-forge/gazebo-feedstock#76]
Reported by @danzimmerman in https://github.com/conda-forge/gazebo-feedstock/issues/45#issuecomment-836723787 . 

This may be related to https://github.com/ignitionrobotics/ign-fuel-tools/pull/178 .

**Comment by Tobias-Fischer** [comment]
Should be fixed by https://github.com/conda-forge/libignition-fuel-tools-feedstock/pull/35

**Comment by danzimmerman** [comment]
@Tobias-Fischer @traversaro I updated Gazebo today and it seems to be fixed:

![image](https://user-images.githubusercontent.com/4365714/123029862-cd2dcb00-d3af-11eb-93a8-5d01c5c87d92.png)
